services:
  php:
    image: ${APP_IMAGE:?Set APP_IMAGE to your ECR image}
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  web:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - /opt/app:/app:ro
      - /opt/app/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/healthz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

networks:
  default:
    name: ksymfony
